name: Build NixOS WSL images

on:
  push:
    tags: ["v*"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: aarch64
            runner: ubuntu-24.04-arm
            config: aarch64
          - arch: x86_64
            runner: ubuntu-24.04
            config: x86_64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        run: |
          curl --proto '=https' --tlsv1.2 -sSf -L https://nixos.org/nix/install | sh -s -- --daemon --yes
          echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
          sudo mkdir -p /etc/nix
          echo "experimental-features = nix-command flakes" | sudo tee /etc/nix/nix.conf

      - name: Build tarball
        run: sudo /nix/var/nix/profiles/default/bin/nix run .#nixosConfigurations.${{ matrix.config }}.config.system.build.tarballBuilder -- nixos-${{ matrix.arch }}.wsl

      - uses: actions/upload-artifact@v4
        with:
          name: nixos-${{ matrix.arch }}.wsl
          path: nixos-${{ matrix.arch }}.wsl

  release:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v2
        with:
          files: "**/*.wsl"
